//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.5.4.0 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace NPS.ID.PublicApi.Models.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class CapacityRow 
    {
        [Newtonsoft.Json.JsonProperty("eventSequenceNo", Required = Newtonsoft.Json.Required.Always)]
        public int EventSequenceNo { get; set; }
    
        [Newtonsoft.Json.JsonProperty("internal", Required = Newtonsoft.Json.Required.Always)]
        public bool Internal { get; set; }
    
        [Newtonsoft.Json.JsonProperty("publicationTime", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset PublicationTime { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deliveryAreaFrom", Required = Newtonsoft.Json.Required.Always)]
        public int DeliveryAreaFrom { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deliveryAreaTo", Required = Newtonsoft.Json.Required.Always)]
        public int DeliveryAreaTo { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deliveryAreaStart", Required = Newtonsoft.Json.Required.Always)]
        public int DeliveryAreaStart { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deliveryAreaEnd", Required = Newtonsoft.Json.Required.Always)]
        public int DeliveryAreaEnd { get; set; }
    
        [Newtonsoft.Json.JsonProperty("inCapacity", Required = Newtonsoft.Json.Required.Always)]
        public int InCapacity { get; set; }
    
        [Newtonsoft.Json.JsonProperty("outCapacity", Required = Newtonsoft.Json.Required.Always)]
        public int OutCapacity { get; set; }
    
        [Newtonsoft.Json.JsonProperty("updatedAt", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset UpdatedAt { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static CapacityRow FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<CapacityRow>(data);
        }
    }
}