//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.5.4.0 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace NPS.ID.PublicApi.Models.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class DeliveryAreaState 
    {
        [Newtonsoft.Json.JsonProperty("dlvryAreaId", Required = Newtonsoft.Json.Required.Always)]
        public int DlvryAreaId { get; set; }
    
        /// <summary>ACTI: Active
        ///                    IACT: Expired(will never be reopened)
        ///                    HIBE: Closed(can be reopened)</summary>
        [Newtonsoft.Json.JsonProperty("state", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public DeliveryAreaStateState State { get; set; }
    
        [Newtonsoft.Json.JsonProperty("openAt", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset OpenAt { get; set; }
    
        [Newtonsoft.Json.JsonProperty("closedAt", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset ClosedAt { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static DeliveryAreaState FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<DeliveryAreaState>(data);
        }
    }
    
    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class ContractRow 
    {
        [Newtonsoft.Json.JsonProperty("contractId", Required = Newtonsoft.Json.Required.AllowNull)]
        public string ContractId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("contractName", Required = Newtonsoft.Json.Required.AllowNull)]
        public string ContractName { get; set; }
    
        /// <summary>ACTI: Active
        ///                    IACT: Expired(will never be reopened)
        ///                    HIBE: Closed(can be reopened)</summary>
        [Newtonsoft.Json.JsonProperty("state", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ContractRowState State { get; set; }
    
        [Newtonsoft.Json.JsonProperty("durationSeconds", Required = Newtonsoft.Json.Required.Always)]
        public int DurationSeconds { get; set; }
    
        [Newtonsoft.Json.JsonProperty("resolutionSeconds", Required = Newtonsoft.Json.Required.Always)]
        public int ResolutionSeconds { get; set; }
    
        [Newtonsoft.Json.JsonProperty("predefined", Required = Newtonsoft.Json.Required.Always)]
        public bool Predefined { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deleted", Required = Newtonsoft.Json.Required.Always)]
        public bool Deleted { get; set; }
    
        [Newtonsoft.Json.JsonProperty("dlvryStart", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset DlvryStart { get; set; }
    
        [Newtonsoft.Json.JsonProperty("dlvryEnd", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset DlvryEnd { get; set; }
    
        [Newtonsoft.Json.JsonProperty("dlvryAreaState", Required = Newtonsoft.Json.Required.AllowNull)]
        public System.Collections.Generic.List<DeliveryAreaState> DlvryAreaState { get; set; }
    
        [Newtonsoft.Json.JsonProperty("marketId", Required = Newtonsoft.Json.Required.AllowNull)]
        public string MarketId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("shortDisplayName", Required = Newtonsoft.Json.Required.AllowNull)]
        public string ShortDisplayName { get; set; }
    
        [Newtonsoft.Json.JsonProperty("mediumDisplayName", Required = Newtonsoft.Json.Required.AllowNull)]
        public string MediumDisplayName { get; set; }
    
        [Newtonsoft.Json.JsonProperty("productType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ContractRowProductType ProductType { get; set; }
    
        [Newtonsoft.Json.JsonProperty("productId", Required = Newtonsoft.Json.Required.AllowNull)]
        public string ProductId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("updatedAt", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset UpdatedAt { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static ContractRow FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<ContractRow>(data);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public enum DeliveryAreaStateState
    {
        [System.Runtime.Serialization.EnumMember(Value = "HIBE")]
        HIBE = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "IACT")]
        IACT = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "ACTI")]
        ACTI = 2,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public enum ContractRowState
    {
        [System.Runtime.Serialization.EnumMember(Value = "HIBE")]
        HIBE = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "IACT")]
        IACT = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "ACTI")]
        ACTI = 2,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public enum ContractRowProductType
    {
        [System.Runtime.Serialization.EnumMember(Value = "P15MIN")]
        P15MIN = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "P30MIN")]
        P30MIN = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "P60MIN")]
        P60MIN = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "BLOCK_2H")]
        BLOCK_2H = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "BLOCK_4H")]
        BLOCK_4H = 4,
    
        [System.Runtime.Serialization.EnumMember(Value = "DON")]
        DON = 5,
    
        [System.Runtime.Serialization.EnumMember(Value = "DB34")]
        DB34 = 6,
    
        [System.Runtime.Serialization.EnumMember(Value = "DP")]
        DP = 7,
    
        [System.Runtime.Serialization.EnumMember(Value = "DEP")]
        DEP = 8,
    
        [System.Runtime.Serialization.EnumMember(Value = "DB")]
        DB = 9,
    
        [System.Runtime.Serialization.EnumMember(Value = "CUSTOM_BLOCK")]
        CUSTOM_BLOCK = 10,
    
    }
}