//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.5.4.0 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace NPS.ID.PublicApi.Models.Generated
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class HeartBeatItem 
    {
        /// <summary>A topic that the current user is subscribed to</summary>
        [Newtonsoft.Json.JsonProperty("topic", Required = Newtonsoft.Json.Required.AllowNull)]
        public string Topic { get; set; }
    
        /// <summary>Last x-nps-sequenceNo value for packets sent to the topic (see Message sequencing)</summary>
        [Newtonsoft.Json.JsonProperty("lastSequenceNumber", Required = Newtonsoft.Json.Required.Always)]
        public int LastSequenceNumber { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static HeartBeatItem FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<HeartBeatItem>(data);
        }
    }
    
    /// <summary>The Intraday Platform uses Heartbeat Ping messages to inform a client that the server is alive and to let the client perform consistency checking of the data received.</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class HeartbeatMessage 
    {
        /// <summary>Timestamp of the Heartbeat generation in Unix Epoch Milliseconds format.</summary>
        [Newtonsoft.Json.JsonProperty("timestamp", Required = Newtonsoft.Json.Required.Always)]
        public int Timestamp { get; set; }
    
        [Newtonsoft.Json.JsonProperty("heartBeats", Required = Newtonsoft.Json.Required.AllowNull)]
        public System.Collections.Generic.List<HeartBeatItem> HeartBeats { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static HeartbeatMessage FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<HeartbeatMessage>(data);
        }
    }
}