//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.5.4.0 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace NPS.ID.PublicApi.Models.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class HeartBeatItem 
    {
        [Newtonsoft.Json.JsonProperty("topic", Required = Newtonsoft.Json.Required.AllowNull)]
        public string Topic { get; set; }
    
        [Newtonsoft.Json.JsonProperty("lastSequenceNumber", Required = Newtonsoft.Json.Required.Always)]
        public int LastSequenceNumber { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static HeartBeatItem FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<HeartBeatItem>(data);
        }
    }
    
    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class HeartbeatMessage 
    {
        [Newtonsoft.Json.JsonProperty("timestamp", Required = Newtonsoft.Json.Required.Always)]
        public int Timestamp { get; set; }
    
        [Newtonsoft.Json.JsonProperty("heartBeats", Required = Newtonsoft.Json.Required.AllowNull)]
        public System.Collections.Generic.List<HeartBeatItem> HeartBeats { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static HeartbeatMessage FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<HeartbeatMessage>(data);
        }
    }
}