//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.5.4.0 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace NPS.ID.PublicApi.Models.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class Order 
    {
        [Newtonsoft.Json.JsonProperty("orderId", Required = Newtonsoft.Json.Required.AllowNull)]
        public string OrderId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deliveryAreaId", Required = Newtonsoft.Json.Required.Always)]
        public int DeliveryAreaId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("price", Required = Newtonsoft.Json.Required.Always)]
        public int Price { get; set; }
    
        [Newtonsoft.Json.JsonProperty("qty", Required = Newtonsoft.Json.Required.Always)]
        public int Qty { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static Order FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Order>(data);
        }
    }
    
    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class LocalViewRow 
    {
        [Newtonsoft.Json.JsonProperty("buyOrders", Required = Newtonsoft.Json.Required.AllowNull)]
        public System.Collections.Generic.List<Order> BuyOrders { get; set; }
    
        [Newtonsoft.Json.JsonProperty("sellOrders", Required = Newtonsoft.Json.Required.AllowNull)]
        public System.Collections.Generic.List<Order> SellOrders { get; set; }
    
        [Newtonsoft.Json.JsonProperty("contractId", Required = Newtonsoft.Json.Required.AllowNull)]
        public string ContractId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deliveryAreaId", Required = Newtonsoft.Json.Required.Always)]
        public int DeliveryAreaId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("orderExecutionRestriction", Required = Newtonsoft.Json.Required.AllowNull)]
        public string OrderExecutionRestriction { get; set; }
    
        [Newtonsoft.Json.JsonProperty("updatedAt", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset UpdatedAt { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static LocalViewRow FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<LocalViewRow>(data);
        }
    }
}