//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.5.4.0 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace NPS.ID.PublicApi.Models.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class PublicStatisticRow 
    {
        [Newtonsoft.Json.JsonProperty("lastPrice", Required = Newtonsoft.Json.Required.Always)]
        public int LastPrice { get; set; }
    
        [Newtonsoft.Json.JsonProperty("lastQuantity", Required = Newtonsoft.Json.Required.Always)]
        public int LastQuantity { get; set; }
    
        [Newtonsoft.Json.JsonProperty("lastTradeTime", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset LastTradeTime { get; set; }
    
        [Newtonsoft.Json.JsonProperty("highestPrice", Required = Newtonsoft.Json.Required.Always)]
        public int HighestPrice { get; set; }
    
        [Newtonsoft.Json.JsonProperty("lowestPrice", Required = Newtonsoft.Json.Required.Always)]
        public int LowestPrice { get; set; }
    
        [Newtonsoft.Json.JsonProperty("vwap", Required = Newtonsoft.Json.Required.Always)]
        public int Vwap { get; set; }
    
        [Newtonsoft.Json.JsonProperty("turnover", Required = Newtonsoft.Json.Required.Always)]
        public int Turnover { get; set; }
    
        [Newtonsoft.Json.JsonProperty("dayAheadPrice", Required = Newtonsoft.Json.Required.Always)]
        public int DayAheadPrice { get; set; }
    
        [Newtonsoft.Json.JsonProperty("tendency", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PublicStatisticRowTendency Tendency { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static PublicStatisticRow FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<PublicStatisticRow>(data);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public enum PublicStatisticRowTendency
    {
        [System.Runtime.Serialization.EnumMember(Value = "UP")]
        UP = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "DOWN")]
        DOWN = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "EQUAL")]
        EQUAL = 2,
    
    }
}