//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v9.5.4.0 (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace NPS.ID.PublicApi.Models.Generated
{
    #pragma warning disable // Disable all warnings

    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class PublicTradeLeg 
    {
        [Newtonsoft.Json.JsonProperty("ownership", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PublicTradeLegOwnership Ownership { get; set; }
    
        [Newtonsoft.Json.JsonProperty("contractId", Required = Newtonsoft.Json.Required.AllowNull)]
        public string ContractId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("side", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PublicTradeLegSide Side { get; set; }
    
        [Newtonsoft.Json.JsonProperty("unitPrice", Required = Newtonsoft.Json.Required.Always)]
        public int UnitPrice { get; set; }
    
        [Newtonsoft.Json.JsonProperty("quantity", Required = Newtonsoft.Json.Required.Always)]
        public int Quantity { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deliveryAreaId", Required = Newtonsoft.Json.Required.Always)]
        public int DeliveryAreaId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("aggressor", Required = Newtonsoft.Json.Required.Always)]
        public bool Aggressor { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static PublicTradeLeg FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<PublicTradeLeg>(data);
        }
    }
    
    /// <summary>TODO: Description</summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public partial class PublicTradeRow 
    {
        [Newtonsoft.Json.JsonProperty("updatedAt", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset UpdatedAt { get; set; }
    
        [Newtonsoft.Json.JsonProperty("tradeId", Required = Newtonsoft.Json.Required.AllowNull)]
        public string TradeId { get; set; }
    
        [Newtonsoft.Json.JsonProperty("tradeTime", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.DateTimeOffset TradeTime { get; set; }
    
        [Newtonsoft.Json.JsonProperty("state", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PublicTradeRowState State { get; set; }
    
        [Newtonsoft.Json.JsonProperty("legs", Required = Newtonsoft.Json.Required.AllowNull)]
        public System.Collections.Generic.List<PublicTradeLeg> Legs { get; set; }
    
        [Newtonsoft.Json.JsonProperty("currency", Required = Newtonsoft.Json.Required.AllowNull)]
        public string Currency { get; set; }
    
        [Newtonsoft.Json.JsonProperty("eventSequenceNo", Required = Newtonsoft.Json.Required.Always)]
        public int EventSequenceNo { get; set; }
    
        [Newtonsoft.Json.JsonProperty("deleted", Required = Newtonsoft.Json.Required.Always)]
        public bool Deleted { get; set; }
    
        [Newtonsoft.Json.JsonProperty("mediumDisplayName", Required = Newtonsoft.Json.Required.AllowNull)]
        public string MediumDisplayName { get; set; }
    
        public string ToJson() 
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this);
        }
        
        public static PublicTradeRow FromJson(string data)
        {
            return Newtonsoft.Json.JsonConvert.DeserializeObject<PublicTradeRow>(data);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public enum PublicTradeLegOwnership
    {
        [System.Runtime.Serialization.EnumMember(Value = "OWN_BUY")]
        OWN_BUY = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "OWN_SELL")]
        OWN_SELL = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "COMPANY_BUY")]
        COMPANY_BUY = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "COMPANY_SELL")]
        COMPANY_SELL = 3,
    
        [System.Runtime.Serialization.EnumMember(Value = "OTHER")]
        OTHER = 4,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public enum PublicTradeLegSide
    {
        [System.Runtime.Serialization.EnumMember(Value = "BUY")]
        BUY = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "SELL")]
        SELL = 1,
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.5.4.0")]
    public enum PublicTradeRowState
    {
        [System.Runtime.Serialization.EnumMember(Value = "COMPLETED")]
        COMPLETED = 0,
    
        [System.Runtime.Serialization.EnumMember(Value = "DISPUTED")]
        DISPUTED = 1,
    
        [System.Runtime.Serialization.EnumMember(Value = "NOT_CANCELLED")]
        NOT_CANCELLED = 2,
    
        [System.Runtime.Serialization.EnumMember(Value = "CANCELLED")]
        CANCELLED = 3,
    
    }
}